////////////////////////////////////////////////////////////////////////
//
// LA Developer - RAD with LA SDK
//
// Author    : LA Center Corporation (la@liveapps.center)
// Copyright : 2016 LA Center Corporation
//
////////////////////////////////////////////////////////////////////////

uses 'globals';

procedure createMainImages(form: TForm);
begin
    mainImages := TImageList.Create(form);
    mainImages.Name := 'mainImages';
    toolboxImages := TImageList.Create(form);
    toolboxImages.Name := 'ToolboxImages';
    mainImages32 := TImageList.Create(form);
    mainImages32.Name := 'mainImages32';
    mainImages32.Width := 32;
    mainImages32.Height := 32;

    mainImages.AddFromResource('bmp_newproject', clWhite);          //0
    mainImages.AddFromResource('bmp_createunit', clFuchsia);        //1
    mainImages.AddFromResource('bmp_createform', clFuchsia);        //2
    mainImages.AddFromResource('bmp_openproject', clFuchsia);       //3
    mainImages.AddFromResource('bmp_save', clFuchsia);              //4
    mainImages.AddFromResource('bmp_saveall', clFuchsia);           //5
    mainImages.AddFromResource('bmp_undo', clFuchsia);              //6
    mainImages.AddFromResource('bmp_redo', clFuchsia);              //7
    mainImages.AddFromResource('bmp_cut', clFuchsia);               //8
    mainImages.AddFromResource('bmp_copy', clFuchsia);              //9
    mainImages.AddFromResource('bmp_paste', clFuchsia);             //10
    mainImages.AddFromResource('bmp_props', clFuchsia);             //11
    mainImages.AddFromResource('bmp_events', clFuchsia);            //12
    mainImages.AddFromResource('bmp_fclose', clWhite);              //13 -
    mainImages.AddFromResource('bmp_fopen', clWhite);               //14 -
    mainImages.AddFromResource('bmp_vb', clWhite);                  //15
    mainImages.AddFromResource('bmp_cpp', clWhite);                 //16
    mainImages.AddFromResource('bmp_js', clWhite);                  //17
    mainImages.AddFromResource('bmp_pas', clWhite);                 //18
    mainImages.AddFromResource('bmp_unit', clFuchsia);              //19
    mainImages.AddFromResource('bmp_form', clFuchsia);              //20
    mainImages.AddFromResource('bmp_project', clFuchsia);           //21
    mainImages.AddFromResource('bmp_open', clFuchsia);              //22
    mainImages.AddFromResource('bmp_run', clFuchsia);               //23
    mainImages.AddFromResource('bmp_debug', clFuchsia);             //24
    mainImages.AddFromResource('bmp_step', clFuchsia);              //25
    mainImages.AddFromResource('bmp_compile', clFuchsia);           //26
    mainImages.AddFromResource('bmp_build', clWhite);               //27
    mainImages.AddFromResource('bmp_newunit', clFuchsia);           //28
    mainImages.AddFromResource('bmp_addunit', clFuchsia);           //29
    mainImages.AddFromResource('bmp_close', clFuchsia);             //30
    mainImages.AddFromResource('bmp_closeall', clFuchsia);          //31
    mainImages.AddFromResource('bmp_exit', clFuchsia);              //32
    mainImages.AddFromResource('bmp_bring2front', clFuchsia);       //33
    mainImages.AddFromResource('bmp_send2back', clFuchsia);         //34
    mainImages.AddFromResource('bmp_alignleft', clFuchsia);         //35
    mainImages.AddFromResource('bmp_alignright', clFuchsia);        //36
    mainImages.AddFromResource('bmp_aligntop', clFuchsia);          //37
    mainImages.AddFromResource('bmp_alignbottom', clFuchsia);       //38
    mainImages.AddFromResource('bmp_alignhorz', clFuchsia);         //39
    mainImages.AddFromResource('bmp_alignvert', clFuchsia);         //40
    mainImages.AddFromResource('bmp_size', clFuchsia);              //41
    mainImages.AddFromResource('bmp_taborder', clFuchsia);          //42
    mainImages.AddFromResource('bmp_changeparent', clFuchsia);      //43
    mainImages.AddFromResource('bmp_delete', clFuchsia);            //44
    mainImages.AddFromResource('bmp_goto', clFuchsia);              //45
    mainImages.AddFromResource('bmp_find', clFuchsia);              //46
    mainImages.AddFromResource('bmp_findprev', clFuchsia);          //47
    mainImages.AddFromResource('bmp_findnext', clFuchsia);          //48
    mainImages.AddFromResource('bmp_findfolder', clFuchsia);        //49
    mainImages.AddFromResource('bmp_findobj', clWhite);             //50
    mainImages.AddFromResource('bmp_replace', clWhite);             //51
    mainImages.AddFromResource('bmp_replacefolder', clWhite);       //52
    mainImages.AddFromResource('bmp_mainunit', clFuchsia);          //53
    mainImages.AddFromResource('bmp_delunit', clFuchsia);           //54
    mainImages.AddFromResource('bmp_editunit', clFuchsia);          //55
    mainImages.AddFromResource('bmp_runparams', clFuchsia);         //56
    mainImages.AddFromResource('bmp_properties', clFuchsia);        //57
    mainImages.AddFromResource('bmp_break', clFuchsia);             //58
    mainImages.AddFromResource('bmp_codetemp', clFuchsia);          //59
    mainImages.AddFromResource('bmp_scriptmanager', clFuchsia);     //60
    mainImages.AddFromResource('bmp_execscript', clWhite);          //61
    mainImages.AddFromResource('bmp_sqldeveloper', clFuchsia);      //62
    mainImages.AddFromResource('bmp_setup', clFuchsia);             //63
    mainImages.AddFromResource('bmp_text', clFuchsia);              //64
    mainImages.AddFromResource('bmp_exttools', clFuchsia);          //65
    mainImages.AddFromResource('bmp_exectool', clFuchsia);          //66
    mainImages.AddFromResource('bmp_quickref', clFuchsia);          //67
    mainImages.AddFromResource('bmp_userguide', clFuchsia);         //68
    mainImages.AddFromResource('bmp_support', clFuchsia);           //69
    mainImages.AddFromResource('bmp_todo', clFuchsia);              //70
    mainImages.AddFromResource('bmp_targets', clWhite);             //71
    mainImages.AddFromResource('bmp_liveapps', clFuchsia);          //72
    mainImages.AddFromResource('bmp_frame', clFuchsia);             //73
    mainImages.AddFromResource('bmp_report', clFuchsia);            //74
    mainImages.AddFromResource('bmp_module', clFuchsia);            //75
    mainImages.AddFromResource('bmp_newframe', clFuchsia);          //76
    mainImages.AddFromResource('bmp_newreport', clFuchsia);         //77
    mainImages.AddFromResource('bmp_newmodule', clFuchsia);         //78
    mainImages.AddFromResource('bmp_object', clFuchsia);            //79
    mainImages.AddFromResource('bmp_control', clFuchsia);           //80
    mainImages.AddFromResource('bmp_move', clFuchsia);              //81
    mainImages.AddFromResource('bmp_continue', clFuchsia);          //82
    mainImages.AddFromResource('bmp_info', clFuchsia);              //83
    mainImages.AddFromResource('bmp_error', clFuchsia);             //84
    mainImages.AddFromResource('bmp_logo', clWhite);                //85
    mainImages.AddFromResource('bmp_done', clFuchsia);              //86
    mainImages.AddFromResource('bmp_resources', clWhite);           //87
    mainImages.AddFromResource('bmp_selall', clFuchsia);            //88
    mainImages.AddFromResource('bmp_rename', clFuchsia);            //89
    mainImages.AddFromResource('bmp_store', clFuchsia);             //90
    mainImages.AddFromResource('bmp_db', clFuchsia);                //91
    mainImages.AddFromResource('bmp_user', clFuchsia);              //92
    mainImages.AddFromResource('bmp_node', clFuchsia);              //93
    mainImages.AddFromResource('bmp_nodeitem', clFuchsia);          //94
    mainImages.AddFromResource('bmp_app', clFuchsia);               //95
    mainImages.AddFromResource('bmp_publish', clFuchsia);           //96
    mainImages.AddFromResource('bmp_class', clWhite);               //97
    mainImages.AddFromResource('bmp_prop', clFuchsia);              //98
    mainImages.AddFromResource('bmp_func', clFuchsia);              //99
    mainImages.AddFromResource('bmp_proc', clFuchsia);              //100
    mainImages.AddFromResource('bmp_event2', clFuchsia);            //101
    mainImages.AddFromResource('bmp_types', clFuchsia);             //102
    mainImages.AddFromResource('bmp_vars', clFuchsia);              //103
    mainImages.AddFromResource('bmp_source', clWhite);              //104
    mainImages.AddFromResource('bmp_libs', clFuchsia);              //105

    mainImages32.AddFromResource('bmp_cli', clFuchsia);             //0
    mainImages32.AddFromResource('bmp_cgi', clFuchsia);             //1
    mainImages32.AddFromResource('bmp_fcgi', clFuchsia);            //2
    mainImages32.AddFromResource('bmp_http', clFuchsia);            //3
    mainImages32.AddFromResource('bmp_ui', clFuchsia);              //4
    mainImages32.AddFromResource('bmp_mob', clFuchsia);             //5
    mainImages32.AddFromResource('bmp_web', clFuchsia);             //6
    mainImages32.AddFromResource('bmp_vb32', clWhite);              //7
    mainImages32.AddFromResource('bmp_cpp32', clWhite);             //8
    mainImages32.AddFromResource('bmp_js32', clWhite);              //9
    mainImages32.AddFromResource('bmp_pas32', clWhite);             //10
    mainImages32.AddFromResource('bmp_noover', clFuchsia);          //11

    toolboxImages.AddFromResource('tb_select', clFuchsia);          //0
    toolboxImages.AddFromResource('bmp_fclose', clWhite);           //1 -
    toolboxImages.AddFromResource('bmp_fopen', clWhite);            //2 -
    toolboxImages.AddFromResource('tb_action', clFuchsia);          //3
    toolboxImages.AddFromResource('tb_actionlist', clFuchsia);      //4
    toolboxImages.AddFromResource('tb_process', clFuchsia);         //5
    toolboxImages.AddFromResource('tb_processutf', clFuchsia);      //6
    toolboxImages.AddFromResource('tb_processasync', clFuchsia);    //7
    toolboxImages.AddFromResource('tb_calcdialog', clFuchsia);      //8
    toolboxImages.AddFromResource('tb_calendardialog', clFuchsia);  //9
    toolboxImages.AddFromResource('tb_colordialog', clFuchsia);     //10
    toolboxImages.AddFromResource('tb_datasource', clWhite);        //11
    toolboxImages.AddFromResource('tb_fbevent', clWhite);           //12
    toolboxImages.AddFromResource('tb_pqevent', clWhite);           //13
    toolboxImages.AddFromResource('tb_finddialog', clFuchsia);      //14
    toolboxImages.AddFromResource('tb_fontdialog', clFuchsia);      //15
    toolboxImages.AddFromResource('tb_ibadmin', clFuchsia);         //16
    toolboxImages.AddFromResource('tb_ibconnection', clFuchsia);    //17
    toolboxImages.AddFromResource('tb_imagelist', clFuchsia);       //18
    toolboxImages.AddFromResource('tb_mssqlconnection', clFuchsia); //19
    toolboxImages.AddFromResource('tb_mainmenu', clFuchsia);        //20
    toolboxImages.AddFromResource('tb_popupmenu', clFuchsia);       //21
    toolboxImages.AddFromResource('tb_mysql40conn', clFuchsia);     //22
    toolboxImages.AddFromResource('tb_mysql41conn', clFuchsia);     //23
    toolboxImages.AddFromResource('tb_mysql50conn', clFuchsia);     //24
    toolboxImages.AddFromResource('tb_mysql51conn', clFuchsia);     //25
    toolboxImages.AddFromResource('tb_mysql55conn', clFuchsia);     //26
    toolboxImages.AddFromResource('tb_mysql56conn', clFuchsia);     //27
    toolboxImages.AddFromResource('tb_odbcconn', clFuchsia);        //28
    toolboxImages.AddFromResource('tb_opendialog', clFuchsia);      //29
    toolboxImages.AddFromResource('tb_savedialog', clFuchsia);      //30
    toolboxImages.AddFromResource('tb_openpicdialog', clFuchsia);   //31
    toolboxImages.AddFromResource('tb_savepicdialog', clFuchsia);   //32
    toolboxImages.AddFromResource('tb_oracleconn', clFuchsia);      //33
    toolboxImages.AddFromResource('tb_pqconn', clFuchsia);          //34
    toolboxImages.AddFromResource('tb_pagesetupdialog', clFuchsia); //35
    toolboxImages.AddFromResource('tb_previewdialog', clFuchsia);   //36
    toolboxImages.AddFromResource('tb_printdialog', clFuchsia);     //37
    toolboxImages.AddFromResource('tb_printersetup', clFuchsia);    //38
    toolboxImages.AddFromResource('tb_draftfilter', clFuchsia);     //39
    toolboxImages.AddFromResource('tb_pdffilter', clFuchsia);       //40
    toolboxImages.AddFromResource('tb_richfilter', clFuchsia);      //41
    toolboxImages.AddFromResource('tb_xlsfilter', clFuchsia);       //42
    toolboxImages.AddFromResource('tb_replacedialog', clFuchsia);   //43
    toolboxImages.AddFromResource('tb_sqlquery', clFuchsia);        //44
    toolboxImages.AddFromResource('tb_sqlscript', clFuchsia);       //45
    toolboxImages.AddFromResource('tb_sqltransaction', clFuchsia);  //46
    toolboxImages.AddFromResource('tb_sqliteconn', clFuchsia);      //47
    toolboxImages.AddFromResource('tb_script', clFuchsia);          //48
    toolboxImages.AddFromResource('tb_seldir', clFuchsia);          //49
    toolboxImages.AddFromResource('tb_sybaseconn', clFuchsia);      //50
    toolboxImages.AddFromResource('tb_timer', clFuchsia);           //51
    toolboxImages.AddFromResource('tb_vars', clFuchsia);            //52
    toolboxImages.AddFromResource('tb_xmldataset', clFuchsia);      //53

    toolboxImages.AddFromResource('tb_atabs', clFuchsia);           //54
    toolboxImages.AddFromResource('tb_arrow', clFuchsia);           //55
    toolboxImages.AddFromResource('tb_bgrabutton', clFuchsia);      //56
    toolboxImages.AddFromResource('tb_bgralabel', clFuchsia);       //57
    toolboxImages.AddFromResource('tb_bgralabelfx', clFuchsia);     //58
    toolboxImages.AddFromResource('tb_bgraled', clFuchsia);         //59
    toolboxImages.AddFromResource('tb_bgrapanel', clFuchsia);       //60
    toolboxImages.AddFromResource('tb_bevel', clFuchsia);           //61
    toolboxImages.AddFromResource('tb_bitbtn', clFuchsia);          //62
    toolboxImages.AddFromResource('tb_bubble', clFuchsia);          //63
    toolboxImages.AddFromResource('tb_button', clFuchsia);          //64
    toolboxImages.AddFromResource('tb_buttonpanel', clFuchsia);     //65
    toolboxImages.AddFromResource('tb_calcedit', clFuchsia);        //66
    toolboxImages.AddFromResource('tb_calendar', clFuchsia);        //67
    toolboxImages.AddFromResource('tb_checkbox', clFuchsia);        //68
    toolboxImages.AddFromResource('tb_checkgroup', clFuchsia);      //69
    toolboxImages.AddFromResource('tb_checklistbox', clFuchsia);    //70
    toolboxImages.AddFromResource('tb_chrome', clFuchsia);          //71
    toolboxImages.AddFromResource('tb_circleprogress', clFuchsia);  //72
    toolboxImages.AddFromResource('tb_circleshape', clFuchsia);     //73
    toolboxImages.AddFromResource('tb_colorbox', clFuchsia);        //74
    toolboxImages.AddFromResource('tb_colorbutton', clFuchsia);     //75
    toolboxImages.AddFromResource('tb_colorlistbox', clFuchsia);    //76
    toolboxImages.AddFromResource('tb_combobox', clFuchsia);        //77
    toolboxImages.AddFromResource('tb_dbcalendar', clFuchsia);      //78
    toolboxImages.AddFromResource('tb_dbcheckbox', clFuchsia);      //79
    toolboxImages.AddFromResource('tb_dbcombobox', clFuchsia);      //80
    toolboxImages.AddFromResource('tb_dbdateedit', clFuchsia);      //81
    toolboxImages.AddFromResource('tb_dbdatepicker', clFuchsia);    //82
    toolboxImages.AddFromResource('tb_dbedit', clFuchsia);          //83
    toolboxImages.AddFromResource('tb_dbgroupbox', clFuchsia);      //84
    toolboxImages.AddFromResource('tb_dbimage', clFuchsia);         //85
    toolboxImages.AddFromResource('tb_dblistbox', clFuchsia);       //86
    toolboxImages.AddFromResource('tb_dblcombobox', clFuchsia);     //87
    toolboxImages.AddFromResource('tb_dbllistbox', clFuchsia);      //88
    toolboxImages.AddFromResource('tb_dbmemo', clFuchsia);          //89
    toolboxImages.AddFromResource('tb_dbnav', clFuchsia);           //90
    toolboxImages.AddFromResource('tb_dbradiogroup', clFuchsia);    //91
    toolboxImages.AddFromResource('tb_dbtext', clFuchsia);          //92
    toolboxImages.AddFromResource('tb_clock', clFuchsia);           //93
    toolboxImages.AddFromResource('tb_clock2', clFuchsia);          //94
    toolboxImages.AddFromResource('tb_clock3', clFuchsia);          //95
    toolboxImages.AddFromResource('tb_dateedit', clFuchsia);        //96
    toolboxImages.AddFromResource('tb_datetimepicker', clFuchsia);  //97
    toolboxImages.AddFromResource('tb_designer', clFuchsia);        //98
    toolboxImages.AddFromResource('tb_diredit', clFuchsia);         //99
    toolboxImages.AddFromResource('tb_drawgrid', clFuchsia);        //100
    toolboxImages.AddFromResource('tb_stringgrid', clFuchsia);      //101
    toolboxImages.AddFromResource('tb_worksheet', clFuchsia);       //102
    toolboxImages.AddFromResource('tb_ecprogress', clFuchsia);      //103
    toolboxImages.AddFromResource('tb_ruler', clFuchsia);           //104
    toolboxImages.AddFromResource('tb_ecslider', clFuchsia);        //105
    toolboxImages.AddFromResource('tb_switch', clFuchsia);          //106
    toolboxImages.AddFromResource('tb_edit', clFuchsia);            //107
    toolboxImages.AddFromResource('tb_editbutton', clFuchsia);      //108
    toolboxImages.AddFromResource('tb_ellipseshape', clFuchsia);    //109
    toolboxImages.AddFromResource('tb_filelistbox', clFuchsia);     //110
    toolboxImages.AddFromResource('tb_filenameedit', clFuchsia);    //111
    toolboxImages.AddFromResource('tb_filtercombobox', clFuchsia);  //112
    toolboxImages.AddFromResource('tb_floatspin', clFuchsia);       //113
    toolboxImages.AddFromResource('tb_spin', clFuchsia);            //114
    toolboxImages.AddFromResource('tb_gradient', clFuchsia);        //115
    toolboxImages.AddFromResource('tb_groupbox', clFuchsia);        //116
    toolboxImages.AddFromResource('tb_header', clFuchsia);          //117
    toolboxImages.AddFromResource('tb_hexagon', clFuchsia);         //118
    toolboxImages.AddFromResource('tb_image', clFuchsia);           //119
    toolboxImages.AddFromResource('tb_label', clFuchsia);           //120
    toolboxImages.AddFromResource('tb_ledindi', clFuchsia);         //121
    toolboxImages.AddFromResource('tb_listbox', clFuchsia);         //122
    toolboxImages.AddFromResource('tb_listview', clFuchsia);        //123
    toolboxImages.AddFromResource('tb_maskedit', clFuchsia);        //124
    toolboxImages.AddFromResource('tb_memo', clFuchsia);            //125
    toolboxImages.AddFromResource('tb_octagon', clFuchsia);         //126
    toolboxImages.AddFromResource('tb_pagecontrol', clFuchsia);     //127
    toolboxImages.AddFromResource('tb_paintbox', clFuchsia);        //128
    toolboxImages.AddFromResource('tb_panel', clFuchsia);           //129
    toolboxImages.AddFromResource('tb_parallel', clFuchsia);        //130
    toolboxImages.AddFromResource('tb_pentagon', clFuchsia);        //131
    toolboxImages.AddFromResource('tb_notify', clFuchsia);          //132
    toolboxImages.AddFromResource('tb_progress', clFuchsia);        //133
    toolboxImages.AddFromResource('tb_rlangle', clFuchsia);         //134
    toolboxImages.AddFromResource('tb_rlband', clFuchsia);          //135
    toolboxImages.AddFromResource('tb_rlbarcode', clFuchsia);       //136
    toolboxImages.AddFromResource('tb_rldbbarcode', clFuchsia);     //137
    toolboxImages.AddFromResource('tb_rldbimage', clFuchsia);       //138
    toolboxImages.AddFromResource('tb_rldbmemo', clFuchsia);        //139
    toolboxImages.AddFromResource('tb_rlresult', clFuchsia);        //140
    toolboxImages.AddFromResource('tb_rlrichtext', clFuchsia);      //141
    toolboxImages.AddFromResource('tb_rldbtext', clFuchsia);        //142
    toolboxImages.AddFromResource('tb_rlimage', clFuchsia);         //143
    toolboxImages.AddFromResource('tb_rllabel', clFuchsia);         //144
    toolboxImages.AddFromResource('tb_rlmemo', clFuchsia);          //145
    toolboxImages.AddFromResource('tb_rlpreview', clFuchsia);       //146
    toolboxImages.AddFromResource('tb_rlreport', clFuchsia);        //147
    toolboxImages.AddFromResource('tb_rlrichtext2', clFuchsia);     //148
    toolboxImages.AddFromResource('tb_rlsub', clFuchsia);           //149
    toolboxImages.AddFromResource('tb_rlsys', clFuchsia);           //150
    toolboxImages.AddFromResource('tb_radiobutton', clFuchsia);     //151
    toolboxImages.AddFromResource('tb_radiogroup', clFuchsia);      //152
    toolboxImages.AddFromResource('tb_rect', clFuchsia);            //153
    toolboxImages.AddFromResource('tb_rect2', clFuchsia);           //154
    toolboxImages.AddFromResource('tb_richmemo', clFuchsia);        //155
    toolboxImages.AddFromResource('tb_roundrect', clFuchsia);       //156
    toolboxImages.AddFromResource('tb_roundsquare', clFuchsia);     //157
    toolboxImages.AddFromResource('tb_scrollbar', clFuchsia);       //158
    toolboxImages.AddFromResource('tb_scrollbox', clFuchsia);       //159
    toolboxImages.AddFromResource('tb_shape', clFuchsia);           //160
    toolboxImages.AddFromResource('tb_shapeprogress', clFuchsia);   //161
    toolboxImages.AddFromResource('tb_shelllistview', clFuchsia);   //162
    toolboxImages.AddFromResource('tb_shelltreeview', clFuchsia);   //163
    toolboxImages.AddFromResource('tb_chart', clFuchsia);           //164
    toolboxImages.AddFromResource('tb_speedbutton', clFuchsia);     //165
    toolboxImages.AddFromResource('tb_splitter', clFuchsia);        //166
    toolboxImages.AddFromResource('tb_square', clFuchsia);          //167
    toolboxImages.AddFromResource('tb_star', clFuchsia);            //168
    toolboxImages.AddFromResource('tb_static', clFuchsia);          //169
    toolboxImages.AddFromResource('tb_statusbar', clFuchsia);       //170
    toolboxImages.AddFromResource('tb_syntaxmemo', clFuchsia);      //171
    toolboxImages.AddFromResource('tb_toggle', clFuchsia);          //172
    toolboxImages.AddFromResource('tb_toolbar', clFuchsia);         //173
    toolboxImages.AddFromResource('tb_trackbar', clFuchsia);        //174
    toolboxImages.AddFromResource('tb_trapez', clFuchsia);          //175
    toolboxImages.AddFromResource('tb_trayicon', clFuchsia);        //176
    toolboxImages.AddFromResource('tb_treeview', clFuchsia);        //177
    toolboxImages.AddFromResource('tb_triangle', clFuchsia);        //178
    toolboxImages.AddFromResource('tb_updown', clFuchsia);          //179
    toolboxImages.AddFromResource('tb_urllink', clFuchsia);         //180
    toolboxImages.AddFromResource('tb_value', clFuchsia);           //181
    toolboxImages.AddFromResource('tb_video', clFuchsia);           //182
    toolboxImages.AddFromResource('tb_barcode', clFuchsia);         //183
    toolboxImages.AddFromResource('tb_dbbarcode', clFuchsia);       //184
    toolboxImages.AddFromResource('tb_dbgrid', clFuchsia);          //185
    toolboxImages.AddFromResource('tb_store', clFuchsia);           //186

    toolboxImages.AddFromResource('tb_receiver', clFuchsia);        //187
    toolboxImages.AddFromResource('tb_camera', clFuchsia);          //188
    toolboxImages.AddFromResource('tb_dialog', clFuchsia);          //189
    toolboxImages.AddFromResource('tb_dclock', clFuchsia);          //190
    toolboxImages.AddFromResource('tb_vscroll', clFuchsia);         //191
    toolboxImages.AddFromResource('tb_imgfileman', clFuchsia);      //192
    toolboxImages.AddFromResource('tb_location', clFuchsia);        //193
    toolboxImages.AddFromResource('tb_pdialog', clFuchsia);         //194
    toolboxImages.AddFromResource('tb_rating', clFuchsia);          //195
    toolboxImages.AddFromResource('tb_sensor', clFuchsia);          //196
    toolboxImages.AddFromResource('tb_share', clFuchsia);           //197
    toolboxImages.AddFromResource('tb_shell', clFuchsia);           //198
    toolboxImages.AddFromResource('tb_sms', clFuchsia);             //199
    toolboxImages.AddFromResource('tb_textfileman', clFuchsia);     //200
    toolboxImages.AddFromResource('tb_yndialog', clFuchsia);        //201
end;

//unit constructor
constructor begin end.

